14-upload-a-file-for-submission
AnnetteScott/Speed pull request #27
Opened 2024-10-07 06:18 UTC by yashsavani19

Accepts Bibtex fornat for submission, and automatically parses the information into the field.

2024-10-07 20:15 UTC, AnnetteScott commented on frontend/src/app/moderator/page.tsx
Why?

2024-10-07 20:15 UTC, AnnetteScott requested changes
These changes do not align with the requirements for the user story

2024-10-07 20:16 UTC, AnnetteScott requested changes
These changes do not align with the requirements for the user story

2024-10-08 02:39 UTC, yashsavani19 reviewed
Fixed the changes required. Now the information shows under suggest article page

2024-10-09 19:36 UTC, AnnetteScott approved these changes

2024-10-14 00:39 UTC, merged